config/routes.rb
require 'sidekiq/web'

class AuthConstraint
  def self.matches?(request)
    request.session[:init] = true # Starts up the session so we can access values from it later.
    request.session['admin']
  end
end

Rails.application.routes.draw do

  post '/auth/:provider/callback', :to => 'sessions#create'
  get '/signout', :to => 'sessions#destroy', :as => :logout
  resources :winrates
  resources :avgstats
  resources :accounts
  resources :players
  resources :matches
  resources :stats
  get '/accounts/:id/matches', to: 'players#index', as: :matchlist

  mount Sidekiq::Web => '/sidekiq', :constraints => AuthConstraint

  root 'stats#index'

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @mqcount = RedisSession.scard(:mq)
    @mqcount_high = RedisSession.scard(:mq_high)
    @ac_count = Account.count
    @matches = Match
    @accounts = Account
    @acc = session['account']
    @pqcount = Pqueue.count
  end
end

app/views/stats/index.html.slim
h1 Global stats
p
  = link_to 'Last matches', @matches
  '  |
  = link_to 'Players', accounts_path
  '  |
  = link_to 'Win Rate by hero', winrates_path
  '  |
  = link_to 'Avg stats by skill bracket', avgstats_path
  - if session['admin']
    '  |
    = link_to 'Workers', '/sidekiq'
p
  | Latest matches queued for processing: #{@mqcount_high}
  br
  | Other matches queued for processing: #{@mqcount}
  br
  | Total matches processed: #{@matches.count}
  br
  | Total accounts added: #{@ac_count}
  br
  | Accounts processed: #{(100.0*(@ac_count - @pqcount)/@ac_count).round(3)}% (#{@ac_count - @pqcount})
  br
  | API requests/10min: #{APILimit.count(:match, 600)}
= @qwe