config/routes.rb
require 'sidekiq/web'

class AuthConstraint
  def self.matches?(request)
    request.session[:init] = true # Starts up the session so we can access values from it later.
    request.session['admin']
  end
end

Rails.application.routes.draw do

  post '/auth/:provider/callback', :to => 'sessions#create'
  get '/signout', :to => 'sessions#destroy', :as => :logout
  resources :winrates
  resources :avgstats
  resources :accounts
  resources :players
  resources :matches
  resources :stats
  get '/accounts/:id/matches', to: 'players#index', as: :matchlist

  mount Sidekiq::Web => '/sidekiq', :constraints => AuthConstraint

  root 'stats#index'

end

app/models/account.rb
class Account
  include Mongoid::Document
  field :account_id, type: Integer # 32bit
  field :steamid, type: Integer    # 64bit
  field :profilestate, type: Integer
  field :personaname, type: String
  field :lastlogoff, type: Integer
  field :profileurl, type: String
  field :avatar, type: String
  field :avatarmedium, type: String
  field :avatarfull, type: String
  field :personastate, type: Integer
  field :primaryclanid, type: BigDecimal
  field :timecreated, type: Integer
  field :personastateflags, type: Integer
  field :gameextrainfo, type: String
  field :gameid, type: Integer
  field :loccountrycode, type: String
  field :locstatecode, type: Integer
  field :communityvisibilitystate, type: Integer
  field :commentpermission, type: Integer
  field :realname, type: String
  field :loccityid, type: Integer
  field :lobbysteamid, type: Integer
  field :last_check, type: DateTime
  field :gameserverip, type: String
  field :gameserversteamid, type: Integer
  has_many :players
  has_many :authorizations

  index({ personaname: 1 }, { unique: false})
  #index({ account_id: 1 }, { unique: true})
  field :_id, type: Integer, default: ->{ account_id }

  def self.add_account(accounts, account_id, player=nil)
    # Adds/updates account from json account data, then links it with player
    matched = accounts.select do |account|
      account['steamid'].to_i == (account_id.to_i + 76561197960265728)
    end
    if account = matched.first
      account['last_check'] = Time.now
      account['account_id'] =  account['steamid'].to_i - 76561197960265728
      s = Redis::Semaphore.new('acc:'+account['account_id'].to_s, expiration: 600, redis: RedisSession)
      s.lock(10)
      criteria = Account.where(id: account_id)
      if criteria.exists?
        return true
      else
        record = Account.new(account)
        Pqueue.find_or_create_by(account_id: account['account_id'])
      end
      if player
        player.account = record
      end
      record.save
      s.unlock
      s.delete!
      return record
    else
      return false
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.page(params[:page])
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  def edit
    Pqueue.find_or_create_by(account_id: params[:id]).update(prio: 10)
    render 'accounts/show'
  end

  def mathces
    render :'matches/index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_id, :steamid, :profilestate, :personaname, :lastlogoff, :profileurl, :avatar, :avatarmedium, :avatarfull, :personastate, :primaryclanid, :timecreated, :personastateflags, :gameextrainfo, :gameid, :loccountrycode, :locstatecode, :last_check)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.slim
h1 Listing accounts

table
  thead
    tr
      th Account
      th Personaname

  tbody
    - @accounts.each do |account|
      tr
        td = account.account_id
        td
          = link_to account.personaname, account
br
= paginate @accounts, total_pages: 50

app/views/accounts/show.html.slim
p#notice = notice

= link_to 'Matches', matchlist_path
br
= link_to 'Update matches', edit_account_path
p
  strong Account:
  = @account.account_id
p
  strong Steamid:
  = @account.steamid
p
  strong Profilestate:
  = @account.profilestate
p
  strong Personaname:
  = @account.personaname
p
  strong Lastlogoff:
  = @account.lastlogoff
p
  strong Profileurl:
  = @account.profileurl
p
  strong Avatar:
  = @account.avatar
p
  strong Avatarmedium:
  = @account.avatarmedium
p
  strong Avatarfull:
  = @account.avatarfull
p
  strong Personastate:
  = @account.personastate
p
  strong Primaryclanid:
  = @account.primaryclanid
p
  strong Timecreated:
  = @account.timecreated
p
  strong Personastateflags:
  = @account.personastateflags
p
  strong Gameextrainfo:
  = @account.gameextrainfo
p
  strong Gameid:
  = @account.gameid
p
  strong Loccountrycode:
  = @account.loccountrycode
p
  strong Locstatecode:
  = @account.locstatecode
p
  strong Last check:
  = @account.last_check